package com.example.ecommerceapp.util;

public enum AppAction {

    ACTION_SET_LANGUAGE_ARABIC("ACTION_SET_LANGUAGE_ARABIC"),
    ACTION_LANGUAGE_DIALOG("ACTION_LANGUAGE_DIALOG"),
    ACTION_ON_BOARDING("ACTION_ON_BOARDING"),
    ACTION_LOGIN("ACTION_LOGIN"),
    ACTION_REGISTER("ACTION_REGISTER"),
    ACTION_GO_LOGIN("ACTION_GO_LOGIN"),
    ACTION_CHANGE_PASSWORD("ACTION_CHANGE_PASSWORD"),
    ACTION_NAV_ITEM("ACTION_NAV_ITEM"),
    ACTION_NAV_HOME("ACTION_NAV_HOME"),
    ACTION_NAV_ORDERS("ACTION_NAV_ORDERS"),
    ACTION_NAV_PERCHES("ACTION_NAV_PERCHES"),
    ACTION_NAV_SETTING("ACTION_NAV_SETTING"),
    ACTION_NAV_SUPPORT("ACTION_NAV_SUPPORT"),
    ACTION_QUIT("ACTION_QUIT"),
    ACTION_HOME("ACTION_HOME"),
    ACTION_GO_DIVISION("ACTION_GO_DIVISION"),
    ACTION_SELECT_SINGLE_CITY("ACTION_SELECT_SINGLE_CITY"),
    ADD_CART("ADD_CART"),
    ACTION_GO_DETAIL("ACTION_GO_DETAIL"),



    ;

    private final String action;

    AppAction(String action) {
        this.action = action;
    }

    public String getAction() {
        return action;
    }
}
